blueprint:
  name: Custom doorbell notifications v2.1
  description: '## Custom blueprint to send an image when your doorbell rings to various platforms:
    
    - Pushover support
    
    - Browser Pop up support
    
    - Hassio phone app (iOS included)
    
    - Android TV / Fire TV
    
    
  Store path for images:
    
    - phone/Android/ios: /config/www/tmp/[name of camera]/
    
    - Pushover/Android TV / Fire tv: /media/[name of camera]/[YearMonthDate]/

    #### Version: `2.1.0` (2024-08-01)
    
    #### Author: Unbreakable
    
    #### Tested on Home Assistant Version: `2024.7.4`
    '
  domain: automation
  input:
    doorbell_sensor:
      name: Doorbell sensor
      description: The Doorbell sensor wich triggers the snapshot creation
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - occupancy
          multiple: false
    camera:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain:
          - camera
          multiple: false
    delay:
      name: Delay (Optional)
      description: Wait before creating camera snapshot
      default: '1.5'
      selector:
        number:
          min: 0.0
          max: 10.0
          unit_of_measurement: seconds
          mode: slider
          step: .1
    notification_title:
      name: Notification title (Optional)
      description: 'Default: "Doorbell"'
      default: Doorbell
    notification_message:
      name: Notification message (Optional)
      description: 'Default: "Someone is at the door"'
      default: 'Someone is at the door'
    tv_notification:
      name: Notify your TV?
      description: Toggle if you want to have a notification on your TV.
        
        More info on https://www.home-assistant.io/integrations/nfandroidtv/ 
      selector:
        boolean: {}
      default: false
    pushover_notification:
      name: Notify your Pushover?
      description: Toggle if you want to have a notification on your pushover service.
        
        More info about Pushover on https://www.home-assistant.io/integrations/pushover/
      selector:
        boolean: {}
      default: false
    popup_notification:
      name: Notify your home assistant browser pop up?
      description: Toggle if you want to have a notification on your home assistant via browser popup?
        
        More info for installing browser popup on https://github.com/thomasloven/hass-browser_mod 
      selector:
        boolean: {}
      default: false
    hassio_notification:
      name: Notify your home assistant?
      description: Toggle if you want to have a notification on your home assistant via Android/iOS?
      selector:
        boolean: {}
      default: false
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications
      selector:
        device:
          integration: mobile_app
          multiple: false
    is_ios:
      name: Is it an iOS device?
      description: Toggle if your selected device runs iOS, default is Android
      selector:
        boolean: {}
      default: false
variables:
  hassio_notification: !input hassio_notification
  pushover_notification: !input pushover_notification
  tv_notification: !input tv_notification
  popup_notification: !input popup_notification
  camera: !input camera
  doorbell_sensor: !input doorbell_sensor
  snapshot_store_path: /media/{{ states[camera].object_id}}/{{now().strftime('%Y%m%d')}}/{{now().strftime('%H%M%S_%f')
    }}.jpg
  delay: !input delay
  is_ios: !input is_ios
  notify_device: !input notify_device
  snapshot_create_file_path: /config/www/tmp/snapshot_{{ states[camera].object_id}}{{now().strftime('_%f') }}.jpg
  snapshot_access_file_path: '{{ snapshot_create_file_path | replace(''/config/www'',''/local'')}}'
  notification_title: !input notification_title
  notification_message: !input notification_message

trigger:
  - platform: state
    entity_id: !input doorbell_sensor
    to: "on"
condition: []
action:
  - delay: '{{ delay }}'
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ hassio_notification != ''False'' }}'
        sequence:
          - service: camera.snapshot
            entity_id: !input camera
            data:
                filename: '{{ snapshot_create_file_path }}'
  - service: camera.snapshot
    entity_id: !input camera
    data:
      filename: "{{ snapshot_store_path }}"
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ pushover_notification != ''False'' }}'
        sequence:
          - service: notify.pushover
            data:
              message: "{{notification_message}}"
              title: "{{ notification_title }}"
              data:
                priority: 1
                sound: siren
                expire: 300
                retry: 30
                attachment: "{{snapshot_store_path}}"
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ tv_notification != ''False'' }}'
        sequence:
          - service: notify.android_tv_fire_tv
            data:
              message: "{{notification_message}}"
              title: "{{ notification_title }}"
              data:
                fontsize: medium
                position: bottom-right
                duration: 15
                transparency: 50%
                color: blue
                interrupt: 1
                image:
                  path: "{{ snapshot_store_path }}"
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ popup_notification != ''False'' }}'
        sequence:
          - service: browser_mod.popup
            metadata: {}
            data:
              dismissable: true
              autoclose: false
              title: "{{ notification_title }}"
              size: wide
              content:
                type: vertical-stack
                cards:
                  - show_state: false
                    show_name: false
                    camera_view: live
                    type: picture-entity
                    camera_image: camera.g4_doorbell_pro_high_resolution_channel
                    entity: binary_sensor.g4dpro_door_doorbell
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ hassio_notification != ''False'' }}'
        sequence:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: '{{ notification_title }}'
            message: '{{ notification_message }}'
            data: '{% set android_data = {"image": "%s"} | format(snapshot_access_file_path)
                %} {% set ios_data = {"attachment": {"url": "%s", "content_type": "JPEG"}} | format(snapshot_access_file_path)
                %} {{ ios_data if is_ios else android_data }}'
